version: "2.1"
services:
  sonarr:
    image: cr.hotio.dev/hotio/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/sonarr/configg:/config
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/sonarr/tv:/data/tv
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/sonarr/downloads:/downloads # Should be the same as the download client's folder
    ports:
      - 8989:8989
    restart: unless-stopped