version: "3"

services:
  pwndrop:
    container_name: pwndrop
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Berlin
      - SECRET_PATH=pwndrop # secret path your admin mgmt interface will be
    image: linuxserver/pwndrop:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker-volumes/pwndrop/config:/config
