---
version: "2.1"
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/docker-volumes/nextcloud/config:/config
      - /mnt/docker-volumes/nextcloud/data:/data
    ports:
      - 9443:443
    restart: unless-stopped
