version: "3"

services:
  papermerge:
    container_name: papermerge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    hostname: papermerge
    image: linuxserver/papermerge:latest
    restart: unless-stopped
    volumes:
      - /mnt/docker-volumes/papermerge/importer_dir:/mnt/media/importer_dir
      - /mnt/docker-volumes/papermerge/config:/config
      - /mnt/docker-volumes/papermerge/data:/data
