version: "3.7"

services:
  gokapi:
    image: f0rc3/gokapi:latest
    container_name: gokapi
    restart: unless-stopped
    ports:
      - 53842:53842
    volumes:
      - /mnt/docker-volumes/gokapi/data:/app/data
      - /mnt/docker-volumes/gokapi/config:/app/config
