version: '3.6'

services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/homer:/www/assets
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
