version: '3.3'

services:
  example:
    image: user/image:tag
    container_name: example
    hostname: example
    #user: 1000:1000
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
      #- /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/docker-volumes/example:/opt/example/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    networks:
      - proxy
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.CHANGEME.rule=Host(`service.example.com`)
    #  - traefik.http.services.CHANGEME.loadbalancer.server.port=8080
    #  - traefik.docker.network=proxy
    #  # Part for optional traefik middlewares
    #  - traefik.http.routers.CHANGEME.middlewares=local-ipwhitelist@file

networks:
  proxy:
    external: true
